- name: Check Bun availability
  ansible.builtin.stat:
    path: "{{ dev_home }}/.bun/bin/bun"
  register: bun_binary

- name: Install Bun # noqa command-instead-of-module
  become: true
  become_user: "{{ dev_user }}"
  ansible.builtin.shell:
    cmd: set -o pipefail && curl -fsSL https://bun.sh/install | bash
    executable: /bin/bash
  environment:
    HOME: "{{ dev_home }}"
  when: not bun_binary.stat.exists
  changed_when: true
