- name: Install neovim build dependencies
  ansible.builtin.package:
    name:
      - ninja-build
      - gettext
      - libtool-bin
      - cmake
      - g++
      - pkg-config
      - unzip
      - curl
    state: present
  tags: neovim

- name: Clone Neovim
  become: true
  become_user: "{{ dev_user }}"
  ansible.builtin.git:
    repo: "https://github.com/neovim/neovim.git"
    dest: "{{ dev_home }}/.config/neovim"
    update: true
    version: master
  environment:
    HOME: "{{ dev_home }}"
  register: neovim_repo
  tags: neovim

- name: Build Neovim # noqa no-handler
  become: true
  become_user: "{{ dev_user }}"
  ansible.builtin.command: make -j 20
  args:
    chdir: "{{ dev_home }}/.config/neovim"
  when: neovim_repo.changed
  changed_when: true
  tags: neovim

- name: Install Neovim binary # noqa no-handler
  ansible.builtin.command: make install
  args:
    chdir: "{{ dev_home }}/.config/neovim"
  when: neovim_repo.changed
  changed_when: true
  tags: neovim

- name: Clone nvim config
  become: true
  become_user: "{{ dev_user }}"
  ansible.builtin.git:
    repo: "https://github.com/blntrsz/nvim"
    dest: "{{ dev_home }}/.config/nvim"
    update: true
    force: true
    version: main
  environment:
    HOME: "{{ dev_home }}"
  tags: neovim
