- name: Install Oh My Zsh
  become: true
  become_user: "{{ dev_user }}"
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ dev_home }}/.oh-my-zsh"
    update: true
    version: master
  environment:
    HOME: "{{ dev_home }}"
  tags: zsh

- name: Configure developer shell
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ dev_user }}"
    group: "{{ dev_user }}"
    mode: "0644"
  loop:
    - src: home/.zshrc
      dest: "{{ dev_home }}/.zshrc"
    - src: home/.zprofile
      dest: "{{ dev_home }}/.zprofile"
    - src: home/.config/aliasrc
      dest: "{{ dev_home }}/.config/aliasrc"
  tags: zsh

- name: Install zsh-autosuggestions
  become: true
  become_user: "{{ dev_user }}"
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "{{ dev_home }}/.oh-my-zsh/plugins/zsh-autosuggestions"
    update: true
    version: master
  environment:
    HOME: "{{ dev_home }}"
  tags: zsh
